config/routes.rb
Rails.application.routes.draw do
  root "static_pages#index"
  resources :manufacturers
  resources :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
  belongs_to :manufacturer

  validates :manufacturer, presence: true
  validates :mileage, presence: true
  validates :year, presence: true, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1920
  }
  validates :color, presence: true
end

app/models/manufacturer.rb
class Manufacturer < ActiveRecord::Base
  has_many :cars

  validates :name, presence: true, uniqueness: true
  validates :country, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    @cars = Car.all
  end

  def new
    @car = Car.new
  end

  def edit
    @car = Car.find(params[:id])
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      flash[:success] = "Car created successfully."
      redirect_to cars_path
    else
      flash.now[:danger] = "Car not created successfully."
      render :new
    end
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      flash[:success] = "Car edited successfully."
      redirect_to cars_path
    else
      flash.now[:danger] = "Car not edited successfully."
      render :edit
    end
  end

  def destroy
    @car = Car.find(params[:id])
    if @car.destroy
      flash[:success] = "Car deleted successfully."
      redirect_to cars_path
    else
      flash.now[:danger] = "Car not deleted."
      redirect_to cars_path
    end
  end

  private
    def car_params
      params.require(:car).permit(
        :mileage,
        :year,
        :color,
        :description,
        :manufacturer_id
      )
    end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.order("name")
  end

  def show
    @manufacturer = Manufacturer.find(params[:id])
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def edit
    @manufacturer = Manufacturer.find(params[:id])
  end

  def create
    @manufacturer = Manufacturer.new(manufacturer_params)
    if @manufacturer.save
      flash[:success] = "Manufacturer created successfully."
      redirect_to manufacturers_path
    else
      flash.now[:danger] = "Manufacturer not created successfully."
      render :new
    end
  end

  def update
    @manufacturer = Manufacturer.find(params[:id])
    if @manufacturer.update(manufacturer_params)
      flash[:success] = "Manufacturer edited successfully."
      redirect_to manufacturers_path
    else
      flash.now[:danger] = "Manufacturer not edited successfully."
      render :edit
    end
  end

  def destroy
    @manufacturer = Manufacturer.find(params[:id])
    if @manufacturer.destroy
      flash[:success] = "Manufacturer deleted successfully."
      redirect_to manufacturers_path
    else
      flash.now[:danger] = "Manufacturer not deleted."
      redirect_to manufacturers_path
    end
  end

  private
    def manufacturer_params
      params.require(:manufacturer).permit(:name, :country)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/views/cars/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= form_for @car do |f| %>
    <% if @car.errors.any? %>
      <div id="error_explanation">
        <h2>
          Yikes! Please fix
          <%= pluralize(@car.errors.count, "error") %>:
        </h2>
        <ul>
          <% @car.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="well">
      <div class="form-group">
        <%= f.label :color, "Color", class: "sr-only" %>
        <%= f.text_field :color, class: "form-control", placeholder: "Color *" %>
      </div>
      <div class="form-group">
        <%= f.label :mileage, "Mileage", class: "sr-only" %>
        <%= f.text_field :mileage, class: "form-control", placeholder: "Mileage *" %>
      </div>
      <div class="form-group">
        <%= f.label :year, class: "sr-only" %>
        <%= f.text_field :year, class: "form-control", placeholder: "Year (at least 1920) *" %>
      </div>
      <div class="form-group">
        <%= f.label :description, class: "sr-only" %>
        <%= f.text_area :description, class: "form-control", placeholder: "Description" %>
      </div>
      <div class="form-group">
        <%= f.label :manufacturer_id %>
        <%= f.select :manufacturer_id, options_from_collection_for_select(Manufacturer.all, :id, :name) %>
      </div>
      <p>
        <%= f.submit "Submit", class: "btn btn-default form-control" %>
      </p>
    </div>
  <% end %>
</div>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>

<%= render "form" %>

app/views/cars/index.html.erb
<h1>
  Cars
  <%= link_to "+", new_car_path, class: "btn btn-default" %>
</h1>

<div class="row">
  <% @cars.each do |car| %>
    <div class="col-sm-6 lead car_container">
      <h4>
        <%= car.year %>
        <%= car.manufacturer.name %> in <%= car.color %>
        <small>(<%= car.mileage %> miles)</small>
      </h4>
      <p>
        <%= car.description ||= "No description provided." %>
      </p>
      <p>

      </p>
      <p>
        <%= link_to "Edit", edit_car_path(car), class: "btn btn-default" %>
        <%= link_to "Delete", car_path(car), method: :delete, class: "btn btn-default" %>
      </p>
    </div>
  <% end %>
</div>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render "form" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vroom Vroom Lot</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "Vroom Vroom", root_path, class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Cars", cars_path %></li>
            <li><%= link_to "Manufacturers", manufacturers_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container col-md-10 col-md-offset-1" id="body_content">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/manufacturers/_form.html.erb
<div class="col-md-6 col-md-offset-3">
  <%= form_for @manufacturer do |f| %>
    <% if @manufacturer.errors.any? %>
      <div id="error_explanation">
        <h2>
          Yikes! Please fix
          <%= pluralize(@manufacturer.errors.count, "error") %>:
        </h2>
        <ul>
          <% @manufacturer.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="well">
      <div class="form-group">
        <%= f.label :name, "Name", class: "sr-only" %>
        <%= f.text_field :name, class: "form-control", placeholder: "Name *" %>
      </div>
      <div class="form-group">
        <%= f.label :country, "Country", class: "sr-only" %>
        <%= f.text_field :country, class: "form-control", placeholder: "Country *" %>
      </div>
      <p>
        <%= f.submit "Submit", class: "btn btn-default form-control" %>
      </p>
    </div>
  <% end %>
</div>

app/views/manufacturers/edit.html.erb
<h1>Edit Manufacturer</h1>

<%= render "form" %>

app/views/manufacturers/index.html.erb
<h1>
  Manufacturers
  <%= link_to "+", new_manufacturer_path, class: "btn btn-default" %>
</h1>

<div class="row lead">
  <% @manufacturers.each do |m| %>
    <div class="col-sm-3">
      <h4><%= m.country %></h4>
      <p>
        <%= link_to "Edit", edit_manufacturer_path(m), class: "btn btn-default" %>
        <%= link_to "Delete", manufacturer_path(m), method: :delete, class: "btn btn-default" %>
      </p>
    </div>
  <% end %>
</div>

app/views/manufacturers/new.html.erb
<h1>New Manufacturer</h1>

<%= render "form" %>

app/views/static_pages/index.html.erb
<h1 class="lead center">
  Browse our <strong>Vroom Vroom Lot</strong> via the links
  above for your next dream car.
</h1>